Repository AY2021S2-CS2103T-T13-2/tp, pull requests merged in 2021-04, with the labels that each got.

#145 Update from super upstream
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.png
  docs/diagrams/StorageClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#143 Re-add Ui.png
  README.md
  docs/images/Ui.png
  docs/index.md
Labels: documentation

#142 Update Documentation
  docs/AboutUs.md
  docs/UserGuide.md
  docs/_includes/head.html
  docs/images/modulebookfavicon.ico
  docs/index.md
  src/main/java/seedu/module/ui/ModuleCard.java
  src/main/java/seedu/module/ui/TaskCard.java
  src/main/resources/images/modulebookicon.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatsPanel.fxml
Labels: documentation

#224 General Update Documentation
  docs/UserGuide.md
  docs/_includes/head.html
  docs/index.md
Labels: documentation

#221 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#218 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#137 Placeholder for refreshCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/module/MainApp.java
  src/main/java/seedu/module/logic/commands/AddCommand.java
  src/main/java/seedu/module/logic/commands/RecurCommand.java
  src/main/java/seedu/module/logic/commands/RefreshCommand.java
  src/main/java/seedu/module/logic/parser/ModuleBookParser.java
  src/main/java/seedu/module/model/Model.java
  src/main/java/seedu/module/model/ModelManager.java
  src/main/java/seedu/module/model/task/Recurrence.java
  src/main/java/seedu/module/model/task/RecurrenceType.java
  src/main/java/seedu/module/model/task/Task.java
  src/main/java/seedu/module/storage/JsonSerializableModuleBook.java
  src/main/java/seedu/module/ui/TaskListPanel.java
  src/test/data/JsonSerializableModuleBookTest/typicalTasksModuleBook.json
  src/test/java/seedu/module/logic/commands/AddCommandTest.java
  src/test/java/seedu/module/logic/commands/CommandTestUtil.java
  src/test/java/seedu/module/logic/commands/RefreshCommandTest.java
  src/test/java/seedu/module/testutil/TaskBuilder.java
  src/test/java/seedu/module/testutil/TypicalTasks.java
Labels: enhancement

#225 Edit favicon for head.html
  docs/_includes/head.html
  docs/team/yhtMinceraft1010X.md
Labels: documentation

#217 Rejects extra arguments in the sort command
  src/main/java/seedu/module/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/module/logic/parser/SortCommandParser.java
Labels: type.Task

#223 fix time parsing and use internal java time exceptions [Not complete]
  src/main/java/seedu/module/logic/commands/AddCommand.java
  src/main/java/seedu/module/logic/commands/EditCommand.java
  src/main/java/seedu/module/model/task/Task.java
  src/main/java/seedu/module/model/task/Time.java
  src/test/java/seedu/module/model/task/TimeTest.java
Labels: type.Task

#232 Add qy-h00.md
  docs/team/qy-h00.md
Labels: documentation

#231 Update user guide
  docs/UserGuide.md
  docs/images/modulebookfavicon.ico
  src/main/resources/images/modulebookicon.png
Labels: documentation

#236 resolve refresh of recurring time bug
  src/main/java/seedu/module/model/task/Time.java
Labels: type.Bug

#239 Update user guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addCommand.png
  docs/images/clearCommand.png
  docs/images/deleteCommand.png
  docs/images/deleteTagCommand.png
  docs/images/doneCommand.png
  docs/images/editCommand.png
  docs/images/findCommand.png
  docs/images/findModuleCommand.png
  docs/images/findTagCommand.png
  docs/images/listCommand.png
  docs/images/modulebookfavicon.ico
  docs/images/notdoneCommand.png
  docs/images/recurCommand.png
  docs/images/refreshCommand.png
  docs/images/sortCommand.png
  docs/images/tagCommand.png
  docs/index.md
  docs/team/aiwassprime.md
  docs/team/qy-h00.md
  docs/team/yhtminceraft1010x.md
  src/main/java/seedu/module/model/task/Workload.java
  src/main/resources/images/modulebookicon.png
  src/test/java/seedu/module/model/task/WorkloadTest.java
Labels: documentation

#230 Update deleteTag to be case-insensitive
  docs/UserGuide.md
  src/main/java/seedu/module/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/module/logic/commands/RecurCommand.java
  src/main/java/seedu/module/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/module/logic/parser/ParserUtil.java
  src/main/java/seedu/module/logic/parser/RecurCommandParser.java
  src/main/java/seedu/module/logic/parser/TagCommandParser.java
  src/main/java/seedu/module/model/tag/Tag.java
  src/test/java/seedu/module/logic/parser/FindTagCommandParserTest.java
  src/test/java/seedu/module/logic/parser/ParserUtilTest.java
  src/test/java/seedu/module/model/tag/TagTest.java
  src/test/java/seedu/module/model/task/DescriptionTest.java
  src/test/java/seedu/module/model/task/ModuleTest.java
  src/test/java/seedu/module/model/task/NameTest.java
  src/test/java/seedu/module/model/task/WorkloadTest.java
Labels: bug

#240 add umergta.md (PPP)
  docs/team/umergta.md
Labels: documentation

#241 Add md for figo2127
  docs/AboutUs.md
  docs/team/figo2127.md
Labels: documentation

#244 Debug to make sure color is assigned accoding to time diff
  src/main/java/seedu/module/ui/TaskListPanel.java
Labels: bug

#246 Add test file for sortCommand and sortParser
  docs/UserGuide.md
  src/main/java/seedu/module/logic/commands/SortCommand.java
  src/main/java/seedu/module/model/task/Description.java
  src/main/java/seedu/module/model/task/Task.java
  src/test/java/seedu/module/logic/commands/SortCommandTest.java
  src/test/java/seedu/module/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/module/testutil/TypicalTasks.java
Labels: type.Task

#247 Modify ModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation

#250 Pr ug update
  docs/UserGuide.md
Labels: documentation

#248 Update user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/images/Ui.png
  docs/images/UiAnnotated.png
  docs/images/addCommand.png
  docs/images/deleteCommand.png
  docs/images/deleteTagCommand.png
  docs/images/doneCommand.png
  docs/images/editCommand.png
  docs/images/findCommand.png
  docs/images/findModuleCommand.png
  docs/images/findTagCommand.png
  docs/images/listCommand.png
  docs/images/notdoneCommand.png
  docs/images/recurCommand.png
  docs/images/refreshCommand.png
  docs/images/sortCommand.png
  docs/images/tagCommand.png
  docs/index.md
  src/main/java/seedu/module/logic/commands/TagCommand.java
  src/main/java/seedu/module/model/ModuleManager.java
Labels: documentation

#255 Update user guide
  docs/UserGuide.md
Labels: documentation

#254 Changes time format check
  docs/UserGuide.md
  src/main/java/seedu/module/model/task/Time.java
Labels: bug

#251 Improves code quality.
  src/main/java/seedu/module/logic/commands/RefreshCommand.java
Labels: enhancement

#259 Ug update limitation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#260 Update ppp
  docs/team/qy-h00.md
  src/main/java/seedu/module/model/ModuleManager.java
Labels: documentation

#258 Fix the bugs of showing workload distribution
  src/main/java/seedu/module/model/ModuleManager.java
Labels: enhancement

#253 Change error message and expand test coverage [Ready for Merging]
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/aiwassprime.md
  docs/team/figo2127.md
  docs/team/johndoe.md
  docs/team/qy-h00.md
  docs/team/umergta.md
  docs/team/yhtminceraft1010x.md
  src/main/java/seedu/module/commons/exceptions/IllegalIntegerException.java
  src/main/java/seedu/module/commons/util/StringUtil.java
  src/main/java/seedu/module/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/module/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/module/logic/parser/DoneCommandParser.java
  src/main/java/seedu/module/logic/parser/EditCommandParser.java
  src/main/java/seedu/module/logic/parser/NotDoneCommandParser.java
  src/main/java/seedu/module/logic/parser/ParserUtil.java
  src/main/java/seedu/module/logic/parser/RecurCommandParser.java
  src/main/java/seedu/module/logic/parser/TagCommandParser.java
  src/test/java/seedu/module/commons/core/GuiSettingsTest.java
  src/test/java/seedu/module/commons/core/VersionTest.java
  src/test/java/seedu/module/commons/core/optionalfield/OptionalFieldTest.java
  src/test/java/seedu/module/commons/util/StringUtilTest.java
  src/test/java/seedu/module/logic/commands/AddCommandTest.java
  src/test/java/seedu/module/logic/commands/CommandResultTest.java
  src/test/java/seedu/module/logic/commands/CommandTestUtil.java
  src/test/java/seedu/module/logic/commands/EditCommandTest.java
  src/test/java/seedu/module/logic/commands/FindModuleCommandTest.java
  src/test/java/seedu/module/logic/commands/SortCommandTest.java
  src/test/java/seedu/module/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/module/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/module/logic/parser/DoneCommandParserTest.java
  src/test/java/seedu/module/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/module/logic/parser/ModuleBookParserTest.java
  src/test/java/seedu/module/logic/parser/NotDoneCommandParserTest.java
  src/test/java/seedu/module/logic/parser/ParserUtilTest.java
  src/test/java/seedu/module/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/module/testutil/TaskBuilder.java
Labels: bug

#256 Add new puml diagram for FindModuleCommand and remove some ab3 occurence
  docs/DeveloperGuide.md
  docs/diagrams/FindModuleSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/FindModuleSequenceDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
Labels: documentation

#245 Add recurrence tests
  src/main/java/seedu/module/logic/parser/RecurCommandParser.java
  src/main/java/seedu/module/model/task/Task.java
  src/test/java/seedu/module/logic/commands/CommandTestUtil.java
  src/test/java/seedu/module/logic/commands/RecurCommandTest.java
  src/test/java/seedu/module/logic/parser/RecurCommandParserTest.java
  src/test/java/seedu/module/model/ModelManagerTest.java
  src/test/java/seedu/module/model/ModuleBookTest.java
  src/test/java/seedu/module/model/ModuleManagerTest.java
  src/test/java/seedu/module/model/task/RecurrenceTest.java
  src/test/java/seedu/module/model/task/TaskTest.java
  src/test/java/seedu/module/model/task/UniqueTaskListTest.java
  src/test/java/seedu/module/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/module/testutil/TypicalTasks.java
Labels: type.Task

#262 update ug
  docs/UserGuide.md
Labels: documentation

#267 Remove extra line from DG
  docs/DeveloperGuide.md
Labels: documentation

#268 update sort use case
  docs/DeveloperGuide.md
Labels: documentation

#273 add page break
  docs/team/umergta.md
Labels: documentation

#276 Add ppp title
  docs/team/figo2127.md
Labels: documentation

#270 Adds hyperlink
  docs/UserGuide.md
Labels: documentation

#271 Update user guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiAnnotated.png
  docs/images/addCommand.png
  docs/images/clearCommand.png
  docs/images/deleteCommand.png
  docs/images/deleteTagCommand.png
  docs/images/doneCommand.png
  docs/images/editCommand.png
  docs/images/findCommand.png
  docs/images/findModuleCommand.png
  docs/images/findTagCommand.png
  docs/images/listCommand.png
  docs/images/notdoneCommand.png
  docs/images/recurCommand.png
  docs/images/refreshCommand.png
  docs/images/sortCommand.png
  docs/images/tagCommand.png
  docs/index.md
Labels: documentation

#272 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/LogicClassDiagram.png
Labels: documentation

#279 Update developer guide
  docs/DeveloperGuide.md
Labels: documentation

#275 Update DG by adding Workload Distribution Feature
  docs/DeveloperGuide.md
  docs/diagrams/WorkloadDistribution.puml
  docs/images/WorkloadDistributionClassDiagram.png
Labels: documentation

#280 Update qy-h00.md
  docs/team/qy-h00.md
Labels: documentation

#281 Update qy-h00.md
  docs/team/qy-h00.md
Labels: documentation

#282 Update AboutUs.md
  docs/AboutUs.md
Labels: documentation

#277 Add tests and remove more ab3 occurences
  src/test/java/seedu/module/logic/commands/FindModuleCommandTest.java
  src/test/java/seedu/module/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/module/testutil/TypicalTasks.java
Labels: priority.Medium

#283 Edit ppp for submission
  docs/team/umergta.md
Labels: documentation

#274 add recur command activity and sequence diagram
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/RecurActivityDiagram.puml
  docs/diagrams/RecurCommandSequenceDiagram.puml
  docs/images/RecurActivityDiagram.png
  docs/images/RecurCommandSequenceDiagram.png
Labels: documentation

#287 Changes comparator
  src/main/java/seedu/module/model/task/Task.java
Labels: bug
