Repository AY2021S2-CS2103T-T13-2/tp, pull requests merged in 2021-03, with the labels that each got.

#41 Update about us
  docs/AboutUs.md
Labels: documentation

#25 Update AboutUs
  docs/AboutUs.md
Labels: documentation

#27 Update readme and _config.yml
  README.md
  docs/_config.yml
Labels: documentation

#49 Update developer guide to include use cases 5-8
  docs/DeveloperGuide.md
Labels: documentation

#48 Update DG (target profile, proposition, user stories)
  docs/DeveloperGuide.md
  docs/images/umergta.png
Labels: documentation

#44 Updates developer guide (First four use cases)
  docs/DeveloperGuide.md
Labels: documentation

#43 Updates user guide (delete, done, notdone)
  docs/UserGuide.md
Labels: documentation

#42 Update UG
  docs/UserGuide.md
Labels: documentation

#47 User Guide Edit description for edit command
  docs/UserGuide.md
Labels: documentation

#53 Update developer guide
  docs/DeveloperGuide.md
Labels: documentation

#55 Update NFRs
  docs/DeveloperGuide.md
Labels: documentation

#72 add photo with correct title and add to AboutUs
  docs/AboutUs.md
  docs/images/umergta.png
  src/main/java/seedu/module/logic/commands/AddCommand.java
Labels: documentation, type.Bug

#66 Fix broken links and typo
  README.md
  docs/index.md
Labels: documentation, priority.High, type.Bug

#68 Update about us
  docs/AboutUs.md
Labels: documentation

#64 Add done not done
  docs/DeveloperGuide.md
  src/main/java/seedu/module/logic/commands/DoneCommand.java
  src/main/java/seedu/module/logic/commands/EditCommand.java
  src/main/java/seedu/module/logic/commands/NotDoneCommand.java
  src/main/java/seedu/module/logic/parser/AddCommandParser.java
  src/main/java/seedu/module/logic/parser/DoneCommandParser.java
  src/main/java/seedu/module/logic/parser/ModuleBookParser.java
  src/main/java/seedu/module/logic/parser/NotDoneCommandParser.java
  src/main/java/seedu/module/model/task/DoneStatus.java
  src/main/java/seedu/module/model/task/Task.java
  src/main/java/seedu/module/model/util/SampleDataUtil.java
  src/main/java/seedu/module/storage/JsonAdaptedTask.java
  src/main/java/seedu/module/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonModuleBookStorageTest/invalidAndValidTaskModuleBook.json
  src/test/data/JsonModuleBookStorageTest/invalidTaskModuleBook.json
  src/test/data/JsonSerializableModuleBookTest/duplicateTaskModuleBook.json
  src/test/data/JsonSerializableModuleBookTest/invalidTaskModuleBook.json
  src/test/data/JsonSerializableModuleBookTest/typicalTasksModuleBook.json
  src/test/java/seedu/module/logic/commands/DoneCommandTest.java
  src/test/java/seedu/module/logic/commands/NotDoneCommandTest.java
  src/test/java/seedu/module/logic/parser/DoneCommandParserTest.java
  src/test/java/seedu/module/logic/parser/ModuleBookParserTest.java
  src/test/java/seedu/module/logic/parser/NotDoneCommandParserTest.java
  src/test/java/seedu/module/model/task/DoneStatusTest.java
  src/test/java/seedu/module/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/module/testutil/TaskBuilder.java
  src/test/java/seedu/module/testutil/TypicalTasks.java
Labels: type.Task

#67 Pr delete and tag
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/module/logic/commands/TagCommand.java
  src/main/java/seedu/module/logic/parser/ModuleBookParser.java
  src/main/java/seedu/module/logic/parser/TagCommandParser.java
  src/test/java/seedu/module/logic/commands/CommandTestUtil.java
  src/test/java/seedu/module/logic/commands/EditCommandTest.java
  src/test/java/seedu/module/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/module/logic/commands/TagCommandTest.java
  src/test/java/seedu/module/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/module/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/module/logic/parser/ModuleBookParserTest.java
  src/test/java/seedu/module/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/module/model/ModuleBookTest.java
  src/test/java/seedu/module/model/task/TaskTest.java
  src/test/java/seedu/module/model/task/UniqueTaskListTest.java
  src/test/java/seedu/module/testutil/TaskUtil.java
  src/test/java/seedu/module/testutil/TypicalTasks.java
Labels: type.Task

#74 Fix typos in test names
  src/test/java/seedu/module/logic/parser/DoneCommandParserTest.java
  src/test/java/seedu/module/logic/parser/NotDoneCommandParserTest.java
Labels: type.Bug

#75 Modify add command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/addTaskUiV1.2.png
  src/main/java/seedu/module/logic/commands/AddCommand.java
  src/main/java/seedu/module/logic/commands/EditCommand.java
  src/main/java/seedu/module/logic/parser/AddCommandParser.java
  src/main/java/seedu/module/logic/parser/CliSyntax.java
  src/main/java/seedu/module/logic/parser/EditCommandParser.java
  src/main/java/seedu/module/logic/parser/TagCommandParser.java
  src/main/java/seedu/module/model/task/DoneStatus.java
  src/main/java/seedu/module/model/task/Task.java
  src/main/java/seedu/module/model/task/UniqueTaskList.java
  src/test/data/JsonSerializableModuleBookTest/duplicateTaskModuleBook.json
  src/test/java/seedu/module/logic/commands/CommandTestUtil.java
  src/test/java/seedu/module/model/task/TaskTest.java
  src/test/java/seedu/module/testutil/TaskUtil.java
  src/test/java/seedu/module/testutil/TypicalTasks.java
Labels: documentation, enhancement, priority.High

#83 Pr tag increment
  docs/UserGuide.md
  src/main/java/seedu/module/logic/commands/TagCommand.java
  src/main/java/seedu/module/logic/parser/TagCommandParser.java
  src/test/java/seedu/module/logic/commands/TagCommandTest.java
  src/test/java/seedu/module/logic/parser/ModuleBookParserTest.java
  src/test/java/seedu/module/logic/parser/TagCommandParserTest.java
Labels: enhancement

#85 Modify deadline, modify and add tests
  docs/UserGuide.md
  src/main/java/seedu/module/model/task/Deadline.java
  src/test/data/JsonModuleBookStorageTest/invalidAndValidTaskModuleBook.json
  src/test/data/JsonModuleBookStorageTest/invalidTaskModuleBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/module/logic/LogicManagerTest.java
  src/test/java/seedu/module/logic/commands/CommandTestUtil.java
  src/test/java/seedu/module/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/module/logic/commands/EditCommandTest.java
  src/test/java/seedu/module/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/module/logic/commands/TagCommandTest.java
  src/test/java/seedu/module/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/module/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/module/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/module/model/ModuleBookTest.java
  src/test/java/seedu/module/model/task/DeadlineTest.java
  src/test/java/seedu/module/model/task/TaskTest.java
  src/test/java/seedu/module/model/task/UniqueTaskListTest.java
  src/test/java/seedu/module/testutil/TypicalTasks.java
Labels: documentation, enhancement, type.Task

#81 Add workload field
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/module/logic/commands/AddCommand.java
  src/main/java/seedu/module/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/module/logic/commands/DoneCommand.java
  src/main/java/seedu/module/logic/commands/EditCommand.java
  src/main/java/seedu/module/logic/commands/NotDoneCommand.java
  src/main/java/seedu/module/logic/commands/TagCommand.java
  src/main/java/seedu/module/logic/parser/AddCommandParser.java
  src/main/java/seedu/module/logic/parser/CliSyntax.java
  src/main/java/seedu/module/logic/parser/EditCommandParser.java
  src/main/java/seedu/module/logic/parser/ParserUtil.java
  src/main/java/seedu/module/model/task/Task.java
  src/main/java/seedu/module/model/task/Workload.java
  src/main/java/seedu/module/model/util/SampleDataUtil.java
  src/main/java/seedu/module/storage/JsonAdaptedTask.java
  src/main/java/seedu/module/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonModuleBookStorageTest/invalidAndValidTaskModuleBook.json
  src/test/data/JsonModuleBookStorageTest/invalidTaskModuleBook.json
  src/test/data/JsonSerializableModuleBookTest/duplicateTaskModuleBook.json
  src/test/data/JsonSerializableModuleBookTest/invalidTaskModuleBook.json
  src/test/data/JsonSerializableModuleBookTest/typicalTasksModuleBook.json
  src/test/java/seedu/module/logic/LogicManagerTest.java
  src/test/java/seedu/module/logic/commands/CommandTestUtil.java
  src/test/java/seedu/module/logic/commands/DoneCommandTest.java
  src/test/java/seedu/module/logic/commands/NotDoneCommandTest.java
  src/test/java/seedu/module/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/module/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/module/logic/parser/ParserUtilTest.java
  src/test/java/seedu/module/model/task/DoneStatusTest.java
  src/test/java/seedu/module/model/task/TaskTest.java
  src/test/java/seedu/module/model/task/WorkloadTest.java
  src/test/java/seedu/module/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/module/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/module/testutil/TaskBuilder.java
  src/test/java/seedu/module/testutil/TaskUtil.java
  src/test/java/seedu/module/testutil/TypicalTasks.java
Labels: type.Task

#86 change message for invalid edit command usage
  src/main/java/seedu/module/logic/commands/EditCommand.java
Labels: type.Bug

#95 Update UGDG and diagrams
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/images/tracing/LogicSequenceDiagram.png
Labels: documentation

#93 Reflect workload tally across various modules
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/module/model/ModuleManager.java
  src/main/java/seedu/module/model/task/Module.java
  src/main/java/seedu/module/model/task/Workload.java
  src/test/java/seedu/module/model/task/ModuleTest.java
  src/test/java/seedu/module/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/module/testutil/TaskUtil.java
Labels: type.Enhancement

#94 Add feature: sort by one factor
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/module/logic/commands/SortCommand.java
  src/main/java/seedu/module/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/module/logic/parser/ModuleBookParser.java
  src/main/java/seedu/module/logic/parser/SortCommandParser.java
  src/main/java/seedu/module/model/Model.java
  src/main/java/seedu/module/model/ModelManager.java
  src/main/java/seedu/module/model/ModuleBook.java
  src/main/java/seedu/module/model/ModuleManager.java
  src/main/java/seedu/module/model/task/Deadline.java
  src/main/java/seedu/module/model/task/Description.java
  src/main/java/seedu/module/model/task/Module.java
  src/main/java/seedu/module/model/task/Name.java
  src/main/java/seedu/module/model/task/Task.java
  src/main/java/seedu/module/model/task/UniqueTaskList.java
  src/main/java/seedu/module/model/task/Workload.java
  src/test/data/JsonModuleBookStorageTest/invalidAndValidTaskModuleBook.json
  src/test/data/JsonModuleBookStorageTest/invalidTaskModuleBook.json
  src/test/java/seedu/module/logic/commands/AddCommandTest.java
  src/test/java/seedu/module/logic/commands/CommandTestUtil.java
  src/test/java/seedu/module/logic/commands/SortCommandTest.java
  src/test/java/seedu/module/logic/parser/ModuleBookParserTest.java
  src/test/java/seedu/module/logic/parser/ParserUtilTest.java
  src/test/java/seedu/module/model/ModelManagerTest.java
  src/test/java/seedu/module/model/task/NameTest.java
  src/test/java/seedu/module/storage/JsonAdaptedTaskTest.java
Labels: type.Enhancement

#96 Pr period
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/module/logic/commands/AddCommand.java
  src/main/java/seedu/module/logic/commands/CommandResult.java
  src/main/java/seedu/module/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/module/logic/commands/DoneCommand.java
  src/main/java/seedu/module/logic/commands/EditCommand.java
  src/main/java/seedu/module/logic/commands/NotDoneCommand.java
  src/main/java/seedu/module/logic/commands/TagCommand.java
  src/main/java/seedu/module/logic/parser/AddCommandParser.java
  src/main/java/seedu/module/logic/parser/CliSyntax.java
  src/main/java/seedu/module/logic/parser/EditCommandParser.java
  src/main/java/seedu/module/logic/parser/ParserUtil.java
  src/main/java/seedu/module/model/task/Task.java
  src/main/java/seedu/module/model/task/Time.java
  src/main/java/seedu/module/model/util/SampleDataUtil.java
  src/main/java/seedu/module/storage/JsonAdaptedTask.java
  src/main/java/seedu/module/ui/TaskCard.java
  src/test/data/JsonSerializableModuleBookTest/duplicateTaskModuleBook.json
  src/test/data/JsonSerializableModuleBookTest/invalidTaskModuleBook.json
  src/test/data/JsonSerializableModuleBookTest/typicalTasksModuleBook.json
  src/test/java/seedu/module/logic/commands/CommandTestUtil.java
  src/test/java/seedu/module/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/module/logic/commands/DoneCommandTest.java
  src/test/java/seedu/module/logic/commands/EditCommandTest.java
  src/test/java/seedu/module/logic/commands/NotDoneCommandTest.java
  src/test/java/seedu/module/logic/commands/TagCommandTest.java
  src/test/java/seedu/module/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/module/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/module/logic/parser/ParserUtilTest.java
  src/test/java/seedu/module/model/task/DeadlineTest.java
  src/test/java/seedu/module/model/task/TaskTest.java
  src/test/java/seedu/module/model/task/TimeTest.java
  src/test/java/seedu/module/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/module/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/module/testutil/TaskBuilder.java
  src/test/java/seedu/module/testutil/TypicalIndexes.java
  src/test/java/seedu/module/testutil/TypicalTasks.java
Labels: enhancement, type.Enhancement

#99 add documentation in UG and DG for recur command
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#100 Add recurring command
  src/main/java/seedu/module/logic/commands/AddCommand.java
  src/main/java/seedu/module/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/module/logic/commands/DoneCommand.java
  src/main/java/seedu/module/logic/commands/EditCommand.java
  src/main/java/seedu/module/logic/commands/NotDoneCommand.java
  src/main/java/seedu/module/logic/commands/RecurCommand.java
  src/main/java/seedu/module/logic/commands/TagCommand.java
  src/main/java/seedu/module/logic/parser/AddCommandParser.java
  src/main/java/seedu/module/logic/parser/CliSyntax.java
  src/main/java/seedu/module/logic/parser/EditCommandParser.java
  src/main/java/seedu/module/logic/parser/ModuleBookParser.java
  src/main/java/seedu/module/logic/parser/ParserUtil.java
  src/main/java/seedu/module/logic/parser/RecurCommandParser.java
  src/main/java/seedu/module/model/Model.java
  src/main/java/seedu/module/model/ModelManager.java
  src/main/java/seedu/module/model/ModuleBook.java
  src/main/java/seedu/module/model/task/Recurrence.java
  src/main/java/seedu/module/model/task/RecurrenceType.java
  src/main/java/seedu/module/model/task/Task.java
  src/main/java/seedu/module/model/task/Time.java
  src/main/java/seedu/module/model/task/UniqueTaskList.java
  src/main/java/seedu/module/storage/JsonAdaptedTask.java
  src/main/java/seedu/module/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonModuleBookStorageTest/invalidTaskModuleBook.json
  src/test/data/JsonSerializableModuleBookTest/duplicateTaskModuleBook.json
  src/test/data/JsonSerializableModuleBookTest/typicalTasksModuleBook.json
  src/test/java/seedu/module/logic/commands/AddCommandTest.java
  src/test/java/seedu/module/logic/commands/CommandTestUtil.java
  src/test/java/seedu/module/logic/commands/EditCommandTest.java
  src/test/java/seedu/module/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/module/model/task/TaskTest.java
  src/test/java/seedu/module/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/module/storage/JsonModuleBookStorageTest.java
  src/test/java/seedu/module/storage/JsonSerializableModuleBookTest.java
  src/test/java/seedu/module/storage/StorageManagerTest.java
  src/test/java/seedu/module/testutil/TaskBuilder.java
  src/test/java/seedu/module/testutil/TypicalTasks.java
Labels: type.Task

#110 Pr code quality
  src/main/java/seedu/module/commons/core/index/Index.java
  src/main/java/seedu/module/commons/core/optionalfield/OptionalField.java
  src/main/java/seedu/module/logic/commands/AddCommand.java
  src/main/java/seedu/module/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/module/logic/commands/DoneCommand.java
  src/main/java/seedu/module/logic/commands/EditCommand.java
  src/main/java/seedu/module/logic/commands/NotDoneCommand.java
  src/main/java/seedu/module/logic/commands/RecurCommand.java
  src/main/java/seedu/module/logic/commands/TagCommand.java
  src/main/java/seedu/module/logic/parser/AddCommandParser.java
  src/main/java/seedu/module/logic/parser/ParserUtil.java
  src/main/java/seedu/module/logic/parser/RecurCommandParser.java
  src/main/java/seedu/module/model/ModuleBook.java
  src/main/java/seedu/module/model/task/Task.java
  src/main/java/seedu/module/model/task/Time.java
  src/main/java/seedu/module/model/task/UniqueTaskList.java
  src/main/java/seedu/module/model/util/SampleDataUtil.java
  src/main/java/seedu/module/storage/JsonAdaptedTask.java
  src/test/java/seedu/module/commons/core/optionalfield/OptionalFieldTest.java
  src/test/java/seedu/module/logic/commands/DoneCommandTest.java
  src/test/java/seedu/module/logic/commands/NotDoneCommandTest.java
  src/test/java/seedu/module/model/task/TimeTest.java
  src/test/java/seedu/module/storage/JsonModuleBookStorageTest.java
  src/test/java/seedu/module/storage/JsonSerializableModuleBookTest.java
  src/test/java/seedu/module/storage/StorageManagerTest.java
  src/test/java/seedu/module/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/module/testutil/TaskBuilder.java
Labels: bug

#115 Fixes bug and add method to delete recur and startTime
  src/main/java/seedu/module/logic/commands/EditCommand.java
  src/main/java/seedu/module/logic/commands/RecurCommand.java
  src/main/java/seedu/module/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/module/logic/parser/EditCommandParser.java
  src/main/java/seedu/module/model/task/Task.java
  src/test/java/seedu/module/logic/commands/CommandTestUtil.java
  src/test/java/seedu/module/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/module/testutil/TaskUtil.java
Labels: bug, enhancement

#119 Bug fix
  src/main/java/seedu/module/model/task/Task.java
Labels: bug

#120 Fix GUI visual glitch
  src/main/java/seedu/module/ui/TaskListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: bug

#122 Add ug info
  docs/UserGuide.md
Labels: documentation

#123 Include screenshots of latest UI into UG
  docs/UserGuide.md
  docs/images/addCommand.png
  docs/images/clearCommand.png
  docs/images/doneCommand.png
  docs/images/editCommand.png
  docs/images/findModuleCommand.png
  docs/images/listCommand.png
  docs/images/recurCommand.png
  docs/images/tagCommand.png
Labels: documentation

#124 fix bug when no message shown with empty recur field
  src/main/java/seedu/module/logic/parser/RecurCommandParser.java
Labels: bug

#132 Update developer guide
  README.md
  docs/SettingUp.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/images/add-remark/$Remark.png
  docs/images/add-remark/CommandInterface.png
  docs/images/add-remark/ContextMenu.png
  docs/images/add-remark/CreateTest.png
  docs/images/add-remark/GradleRun.png
  docs/images/add-remark/ParserInterface.png
  docs/images/add-remark/RemarkBound.png
  docs/images/add-remark/RemarkComplete.png
  docs/images/add-remark/RemarkFailureOutput.png
  docs/images/add-remark/RemarkHello.png
  docs/images/add-remark/RemarkNotImplemented.png
  docs/images/addImageUI.png
  docs/images/addTaskUiV1.2.png
  docs/images/addTaskUiV1.3.png
  docs/images/remove/$address.png
  docs/images/remove/SafeDeleteConflicts.png
  docs/images/remove/UnsafeDelete.png
  docs/images/remove/UnsafeDeleteOnField.png
  docs/images/tracing/DebuggerStep1.png
  docs/images/tracing/EditCommand.png
  docs/images/tracing/Execute.png
  docs/images/tracing/FindUsages.png
  docs/images/tracing/LeftGutter.png
  docs/images/tracing/LogicSequenceDiagram.png
  docs/images/tracing/ShowExecutionPoint.png
  docs/images/tracing/StepInto.png
  docs/images/tracing/StepOver.png
  docs/images/tracing/StructureToolWindow.png
  docs/images/tracing/Variables.png
  docs/index.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
Labels: documentation

#134 fix recur bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/module/logic/commands/RecurCommand.java
  src/main/java/seedu/module/logic/parser/EditCommandParser.java
  src/main/java/seedu/module/logic/parser/RecurCommandParser.java
  src/main/java/seedu/module/model/ModuleBook.java
  src/main/java/seedu/module/model/task/Task.java
Labels: bug

#138 Changes version number
  src/main/java/seedu/module/MainApp.java
Labels: documentation
